name: TaniqueUSA
favicon: null
layout_spectrum: 0.99902
typography_spectrum: 0.61621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#810053'
    - '#faa634'
    - '#d9531e'
    - '#b9739e'
  brandStrength: 0.3670103868935257
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
