name: TaniqueUSA
favicon: null
layout_spectrum: 0.99902
typography_spectrum: 0.61621
title: Luxury Sunless Tanning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a2051'
    - '#efa03f'
    - '#000000'
    - '#2767c8'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
